"""
HotelBound program territory definitions used to decide which deductible clauses
apply to a scheduled location.

Sources:
  - Tier One / Tier Two counties: "Tier 1 and Tier 2 Counties.docx" (HotelBound program
    reference, HUB Drive folder 14-JgUOMUl8bapkuJIvUOF_DBWylNZ0SE).
  - Hail Belt: the "Hail Belt" definition printed in every HotelBound Quotation Memorandum.
    hotelbound_quote.parse_hotelbound_quote() parses the live definition from the quote text
    and only falls back to HAIL_BELT_FALLBACK below when the quote text is unavailable.

County names are matched case-insensitively with "County"/"Parish"/"City" suffixes and
punctuation stripped (see hotelbound_quote._norm_county).
"""

# Named Windstorm Tier One counties — Texas through Virginia group (deductible clauses B and C).
TIER1_TX_VA = {
    "AL": ["Baldwin", "Mobile"],
    "FL": "ALL",
    "GA": ["Bryan", "Camden", "Chatham", "Glynn", "Liberty", "McIntosh"],
    "HI": "ALL",
    "LA": ["Cameron", "Iberia", "Jefferson", "Lafourche", "Orleans", "Plaquemines", "St. Bernard",
           "St. Mary", "St. Tammany", "Terrebonne", "Vermilion"],
    "MS": ["George", "Hancock", "Harrison", "Jackson", "Pearl River", "Stone"],
    "NC": ["Beaufort", "Bertie", "Brunswick", "Camden", "Carteret", "Chowan", "Craven", "Currituck",
           "Dare", "Hyde", "Jones", "New Hanover", "Onslow", "Pamlico", "Pasquotank", "Pender",
           "Perquimans", "Tyrrell", "Washington"],
    "SC": ["Beaufort", "Berkeley", "Charleston", "Colleton", "Dorchester", "Georgetown", "Horry", "Jasper"],
    "TX": ["Aransas", "Brazoria", "Calhoun", "Cameron", "Chambers", "Galveston", "Harris", "Jackson",
           "Jefferson", "Kenedy", "Kleberg", "Matagorda", "Nueces", "Orange", "Refugio", "San Patricio",
           "Victoria", "Willacy"],
    "VA": ["Accomack", "Gloucester", "Hampton City", "Isle of Wight", "Lancaster", "Mathews", "Middlesex",
           "Newport News", "Norfolk City", "Northampton", "Northumberland", "Poquoson City",
           "Portsmouth City", "Southampton", "Suffolk City", "Surry", "Virginia Beach City",
           "Westmoreland", "Williamsburg", "York"],
}

# Named Windstorm Tier One counties — Maryland through Maine group (deductible clause D).
TIER1_MD_ME = {
    "CT": ["Fairfield", "Middlesex", "New Haven", "New London"],
    "DE": ["Kent", "New Castle", "Sussex"],
    "ME": ["Cumberland", "Hancock", "Knox", "Lincoln", "Sagadahoc", "Waldo", "Washington", "York"],
    "MD": ["Anne Arundel", "Baltimore City", "Baltimore", "Calvert", "Caroline", "Cecil", "Dorchester",
           "Harford", "Kent", "Queen Anne's", "St. Mary's", "Somerset", "Talbot", "Wicomico", "Worcester"],
    "MA": ["Barnstable", "Bristol", "Dukes", "Essex", "Nantucket", "Norfolk", "Plymouth", "Suffolk"],
    "NH": ["Rockingham"],
    "NJ": ["Atlantic", "Cape May", "Cumberland", "Hudson", "Middlesex", "Monmouth", "Ocean", "Salem"],
    "NY": ["Bronx", "Kings", "Nassau", "New York", "Queens", "Richmond", "Suffolk", "Westchester"],
    "RI": ["Bristol", "Kent", "Newport", "Providence", "Washington"],
}

# Named Windstorm Tier Two counties / parishes (deductible clause C applies to TX and LA Tier Two;
# the remaining Tier Two states matter for the June 1 - Nov 30 Minimum Earned Premium condition).
TIER2 = {
    "AL": ["Clarke", "Conecuh", "Covington", "Escambia", "Geneva", "Houston", "Monroe", "Washington"],
    "GA": ["Appling", "Brantley", "Brooks", "Bulloch", "Charlton", "Clinch", "Decatur", "Echols",
           "Effingham", "Evans", "Grady", "Long", "Lowndes", "Pierce", "Seminole", "Tattnall", "Thomas",
           "Ware", "Wayne"],
    "LA": ["Acadia", "Allen", "Ascension", "Assumption", "Beauregard", "Calcasieu", "East Baton Rouge",
           "East Feliciana", "Evangeline", "Iberville", "Jefferson Davis", "Lafayette", "Livingston",
           "Pointe Coupee", "St. Charles", "St. Helena", "St. James", "St. John the Baptist", "St. Landry",
           "St. Martin", "Tangipahoa", "Washington", "West Baton Rouge", "West Feliciana"],
    "MS": ["Amite", "Forrest", "George", "Greene", "Lamar", "Marion", "Perry", "Pike", "Stone", "Walthall",
           "Wilkinson"],
    "NC": ["Bertie", "Bladen", "Columbus", "Duplin", "Gates", "Greene", "Halifax", "Hertford", "Lenoir",
           "Martin", "Northampton", "Perquimans", "Pitt", "Robeson", "Sampson"],
    "SC": ["Allendale", "Bamberg", "Clarendon", "Dillon", "Florence", "Hampton", "Marion", "Orangeburg",
           "Williamsburg"],
    "TX": ["Austin", "Bee", "Brooks", "Colorado", "DeWitt", "Duval", "Fort Bend", "Goliad", "Grimes", "Hardin",
           "Hidalgo", "Jasper", "Jim Hogg", "Jim Wells", "Lavaca", "Liberty", "Live Oak", "McMullen",
           "Montgomery", "Newton", "Polk", "San Jacinto", "Starr", "Tyler", "Walker", "Waller", "Wharton"],
    "VA": ["Caroline", "Charles City", "Chesapeake City", "Essex", "Henrico", "James City", "King & Queen",
           "King George", "King William", "New Kent", "Prince George", "Richmond", "Sussex"],
}

# Hail Belt fallback (clause F) — captured from the WG Consolidated Hotel Group quote, Sep 2026.
HAIL_BELT_FALLBACK = {'AR': ['Arkansas', 'Ashley', 'Baxter', 'Benton', 'Boone', 'Bradley', 'Calhoun', 'Carroll', 'Chicot', 'Clark',
        'Clay', 'Cleburne', 'Cleveland', 'Columbia', 'Conway', 'Craighead', 'Crawford', 'Crittenden', 'Cross',
        'Dallas', 'Desha', 'Drew', 'Faulkner', 'Franklin', 'Fulton', 'Garland', 'Grant', 'Greene',
        'Hempstead', 'Hot Spring', 'Howard', 'Independence', 'Izard', 'Jackson', 'Jefferson', 'Johnson',
        'Lafayette', 'Lawrence', 'Lee', 'Lincoln', 'Little River', 'Logan', 'Lonoke', 'Madison', 'Marion',
        'Miller', 'Mississippi', 'Monroe', 'Montgomery', 'Nevada', 'Newton', 'Ouachita', 'Perry', 'Phillips',
        'Pike', 'Poinsett', 'Polk', 'Pope', 'Prairie', 'Pulaski', 'Randolph', 'St. Francis', 'Saline',
        'Scott', 'Searcy', 'Sebastian', 'Sevier', 'Sharp', 'Stone', 'Union', 'Van Buren', 'Washington',
        'White', 'Woodruff', 'Yell'],
 'CO': ['Adams', 'Arapahoe', 'Baca', 'Bent', 'Boulder', 'Broomfield', 'Cheyenne', 'Clear Creek', 'Crowley',
        'Custer', 'Denver', 'Douglas', 'Elbert', 'El Paso', 'Fremont', 'Gilpin', 'Huerfano', 'Jefferson',
        'Kiowa', 'Kit Carson', 'Larimer', 'Lincoln', 'Logan', 'Morgan', 'Otero', 'Phillips', 'Prowers',
        'Pueblo', 'Sedgwick', 'Teller', 'Washington', 'Weld', 'Yuma'],
 'IA': ['Adair', 'Adams', 'Allamakee', 'Appanoose', 'Audubon', 'Benton', 'Black Hawk', 'Boone', 'Bremer',
        'Buchanan', 'Buena Vista', 'Butler', 'Calhoun', 'Carroll', 'Cass', 'Cedar', 'Cerro Gordo', 'Cherokee',
        'Chickasaw', 'Clarke', 'Clay', 'Clayton', 'Clinton', 'Crawford', 'Dallas', 'Davis', 'Decatur',
        'Delaware', 'Des Moines', 'Dickinson', 'Dubuque', 'Emmet', 'Fayette', 'Floyd', 'Franklin', 'Fremont',
        'Greene', 'Grundy', 'Guthrie', 'Hamilton', 'Hancock', 'Hardin', 'Harrison', 'Henry', 'Howard',
        'Humboldt', 'Ida', 'Iowa', 'Jackson', 'Jasper', 'Jefferson', 'Johnson', 'Jones', 'Keokuk', 'Kossuth',
        'Lee', 'Linn', 'Louisa', 'Lucas', 'Lyon', 'Madison', 'Mahaska', 'Marion', 'Marshall', 'Mills',
        'Mitchell', 'Monona', 'Monroe', 'Montgomery', 'Muscatine', "O'Brien", 'Osceola', 'Page', 'Palo Alto',
        'Plymouth', 'Pocahontas', 'Polk', 'Pottawattamie', 'Poweshiek', 'Ringgold', 'Sac', 'Scott', 'Shelby',
        'Sioux', 'Story', 'Tama', 'Taylor', 'Union', 'Van Buren', 'Wapello', 'Warren', 'Washington', 'Wayne',
        'Webster', 'Winnebago', 'Winneshiek', 'Woodbury', 'Worth', 'Wright'],
 'KS': ['Allen', 'Anderson', 'Atchison', 'Barber', 'Barton', 'Bourbon', 'Brown', 'Butler', 'Chase',
        'Chautauqua', 'Cherokee', 'Cheyenne', 'Clark', 'Clay', 'Cloud', 'Coffey', 'Comanche', 'Cowley',
        'Crawford', 'Decatur', 'Dickinson', 'Doniphan', 'Douglas', 'Edwards', 'Elk', 'Ellis', 'Ellsworth',
        'Finney', 'Ford', 'Franklin', 'Geary', 'Gove', 'Graham', 'Grant', 'Gray', 'Greeley', 'Greenwood',
        'Hamilton', 'Harper', 'Harvey', 'Haskell', 'Hodgeman', 'Jackson', 'Jefferson', 'Jewell', 'Johnson',
        'Kearny', 'Kingman', 'Kiowa', 'Labette', 'Lane', 'Leavenworth', 'Lincoln', 'Linn', 'Logan', 'Lyon',
        'McPherson', 'Marion', 'Marshall', 'Meade', 'Miami', 'Mitchell', 'Montgomery', 'Morris', 'Morton',
        'Nemaha', 'Neosho', 'Ness', 'Norton', 'Osage', 'Osborne', 'Ottawa', 'Pawnee', 'Phillips',
        'Pottawatomie', 'Pratt', 'Rawlins', 'Reno', 'Republic', 'Rice', 'Riley', 'Rooks', 'Rush', 'Russell',
        'Saline', 'Scott', 'Sedgwick', 'Seward', 'Shawnee', 'Sheridan', 'Sherman', 'Smith', 'Stafford',
        'Stanton', 'Stevens', 'Sumner', 'Thomas', 'Trego', 'Wabaunsee', 'Wallace', 'Washington', 'Wichita',
        'Wilson', 'Woodson', 'Wyandotte'],
 'MN': ['Aitkin', 'Anoka', 'Becker', 'Beltrami', 'Benton', 'Big Stone', 'Blue Earth', 'Brown', 'Carlton',
        'Carver', 'Cass', 'Chippewa', 'Chisago', 'Clay', 'Clearwater', 'Cook', 'Cottonwood', 'Crow Wing',
        'Dakota', 'Dodge', 'Douglas', 'Faribault', 'Fillmore', 'Freeborn', 'Goodhue', 'Grant', 'Hennepin',
        'Houston', 'Hubbard', 'Isanti', 'Itasca', 'Jackson', 'Kanabec', 'Kandiyohi', 'Kittson', 'Koochiching',
        'Lac Qui Parle', 'Lake', 'Lake Of The Wood', 'Le Sueur', 'Lincoln', 'Lyon', 'Mahnomen', 'Marshall',
        'Martin', 'McLeod', 'Meeker', 'Mille Lacs', 'Morrison', 'Mower', 'Murray', 'Nicollet', 'Nobles',
        'Norman', 'Olmsted', 'Otter Tail', 'Pennington', 'Pine', 'Pipestone', 'Polk', 'Pope', 'Ramsey',
        'Red Lake', 'Redwood', 'Renville', 'Rice', 'Rock', 'Roseau', 'St. Louis', 'Scott', 'Sherburne',
        'Sibley', 'Stearns', 'Steele', 'Stevens', 'Swift', 'Todd', 'Traverse', 'Wabasha', 'Wadena', 'Waseca',
        'Washington', 'Watonwan', 'Wilkin', 'Winona', 'Wright', 'Yellow Medicine'],
 'MO': ['Adair', 'Andrew', 'Atchison', 'Audrain', 'Barry', 'Barton', 'Bates', 'Benton', 'Bollinger', 'Boone',
        'Buchanan', 'Butler', 'Caldwell', 'Callaway', 'Camden', 'Cape Girardeau', 'Carroll', 'Carter', 'Cass',
        'Cedar', 'Chariton', 'Christian', 'Clark', 'Clay', 'Clinton', 'Cole', 'Cooper', 'Crawford', 'Dade',
        'Dallas', 'Daviess', 'DeKalb', 'Dent', 'Douglas', 'Dunklin', 'Franklin', 'Gasconade', 'Gentry',
        'Greene', 'Grundy', 'Harrison', 'Henry', 'Hickory', 'Holt', 'Howard', 'Howell', 'Iron', 'Jackson',
        'Jasper', 'Jefferson', 'Johnson', 'Knox', 'Laclede', 'Lafayette', 'Lawrence', 'Lewis', 'Lincoln',
        'Linn', 'Livingston', 'McDonald', 'Macon', 'Madison', 'Maries', 'Marion', 'Mercer', 'Miller',
        'Mississippi', 'Moniteau', 'Monroe', 'Montgomery', 'Morgan', 'New Madrid', 'Newton', 'Nodaway',
        'Oregon', 'Osage', 'Ozark', 'Pemiscot', 'Perry', 'Pettis', 'Phelps', 'Pike', 'Platte', 'Polk',
        'Pulaski', 'Putnam', 'Ralls', 'Randolph', 'Ray', 'Reynolds', 'Ripley', 'St. Charles', 'St. Clair',
        'Ste. Genevieve', 'St. Francois', 'St. Louis', 'Saline', 'Schuyler', 'Scotland', 'Scott', 'Shannon',
        'Shelby', 'Stoddard', 'Stone', 'Sullivan', 'Taney', 'Texas', 'Vernon', 'Warren', 'Washington',
        'Wayne', 'Webster', 'Worth', 'Wright', 'St. Louis City'],
 'MS': ['Adams', 'Alcorn', 'Amite', 'Attala', 'Benton', 'Bolivar', 'Calhoun', 'Carroll', 'Chickasaw',
        'Choctaw', 'Claiborne', 'Clarke', 'Clay', 'Coahoma', 'Copiah', 'Covington', 'DeSoto', 'Forrest',
        'Franklin', 'George', 'Greene', 'Grenada', 'Hancock', 'Harrison', 'Hinds', 'Holmes', 'Humphreys',
        'Issaquena', 'Itawamba', 'Jackson', 'Jasper', 'Jefferson', 'Jefferson Davis', 'Jones', 'Kemper',
        'Lafayette', 'Lamar', 'Lauderdale', 'Lawrence', 'Leake', 'Lee', 'Leflore', 'Lincoln', 'Lowndes',
        'Madison', 'Marion', 'Marshall', 'Monroe', 'Montgomery', 'Neshoba', 'Newton', 'Noxubee', 'Oktibbeha',
        'Panola', 'Pearl River', 'Perry', 'Pike', 'Pontotoc', 'Prentiss', 'Quitman', 'Rankin', 'Scott',
        'Sharkey', 'Simpson', 'Smith', 'Stone', 'Sunflower', 'Tallahatchie', 'Tate', 'Tippah', 'Tishomingo',
        'Tunica', 'Union', 'Walthall', 'Warren', 'Washington', 'Wayne', 'Webster', 'Wilkinson', 'Winston',
        'Yalobusha', 'Yazoo'],
 'NE': ['Adams', 'Antelope', 'Arthur', 'Banner', 'Blaine', 'Boone', 'Box Butte', 'Boyd', 'Brown', 'Buffalo',
        'Burt', 'Butler', 'Cass', 'Cedar', 'Chase', 'Cherry', 'Cheyenne', 'Clay', 'Colfax', 'Cuming',
        'Custer', 'Dakota', 'Dawes', 'Dawson', 'Deuel', 'Dixon', 'Dodge', 'Douglas', 'Dundy', 'Fillmore',
        'Franklin', 'Frontier', 'Furnas', 'Gage', 'Garden', 'Garfield', 'Gosper', 'Grant', 'Greeley', 'Hall',
        'Hamilton', 'Harlan', 'Hayes', 'Hitchcock', 'Holt', 'Hooker', 'Howard', 'Jefferson', 'Johnson',
        'Kearney', 'Keith', 'Keya Paha', 'Kimball', 'Knox', 'Lancaster', 'Lincoln', 'Logan', 'Loup',
        'McPherson', 'Madison', 'Merrick', 'Morrill', 'Nance', 'Nemaha', 'Nuckolls', 'Otoe', 'Pawnee',
        'Perkins', 'Phelps', 'Pierce', 'Platte', 'Polk', 'Red Willow', 'Richardson', 'Rock', 'Saline',
        'Sarpy', 'Saunders', 'Scotts Bluff', 'Seward', 'Sheridan', 'Sherman', 'Sioux', 'Stanton', 'Thayer',
        'Thomas', 'Thurston', 'Valley', 'Washington', 'Wayne', 'Webster', 'Wheeler', 'York'],
 'OK': ['Adair', 'Alfalfa', 'Atoka', 'Beaver', 'Beckham', 'Blaine', 'Bryan', 'Caddo', 'Canadian', 'Carter',
        'Cherokee', 'Choctaw', 'Cimarron', 'Cleveland', 'Coal', 'Comanche', 'Cotton', 'Craig', 'Creek',
        'Custer', 'Delaware', 'Dewey', 'Ellis', 'Garfield', 'Garvin', 'Grady', 'Grant', 'Greer', 'Harmon',
        'Harper', 'Haskell', 'Hughes', 'Jackson', 'Jefferson', 'Johnston', 'Kay', 'Kingfisher', 'Kiowa',
        'Latimer', 'Le Flore', 'Lincoln', 'Logan', 'Love', 'McClain', 'McCurtain', 'McIntosh', 'Major',
        'Marshall', 'Mayes', 'Murray', 'Muskogee', 'Noble', 'Nowata', 'Okfuskee', 'Oklahoma', 'Okmulgee',
        'Osage', 'Ottawa', 'Pawnee', 'Payne', 'Pittsburg', 'Pontotoc', 'Pottawatomie', 'Pushmataha',
        'Roger Mills', 'Rogers', 'Seminole', 'Sequoyah', 'Stephens', 'Texas', 'Tillman', 'Tulsa', 'Wagoner',
        'Washington', 'Washita', 'Woods', 'Woodward'],
 'SD': ['Aurora', 'Beadle', 'Bennett', 'Bon Homme', 'Brookings', 'Brown', 'Brule', 'Buffalo', 'Butte',
        'Campbell', 'Charles Mix', 'Clark', 'Clay', 'Codington', 'Corson', 'Custer', 'Davison', 'Day',
        'Deuel', 'Dewey', 'Douglas', 'Edmunds', 'Fall River', 'Faulk', 'Grant', 'Gregory', 'Haakon', 'Hamlin',
        'Hand', 'Hanson', 'Harding', 'Hughes', 'Hutchinson', 'Hyde', 'Jackson', 'Jerauld', 'Jones',
        'Kingsbury', 'Lake', 'Lawrence', 'Lincoln', 'Lyman', 'McCook', 'McPherson', 'Marshall', 'Meade',
        'Mellette', 'Miner', 'Minnehaha', 'Moody', 'Pennington', 'Perkins', 'Potter', 'Roberts', 'Sanborn',
        'Shannon', 'Spink', 'Stanley', 'Sully', 'Todd', 'Tripp', 'Turner', 'Union', 'Walworth', 'Yankton',
        'Ziebach'],
 'TX': 'ALL'}
